### ISSUE TITLE
Question: Use of Fixed Ports in `SingleProcessSettings`

### ISSUE THREAD

**Issue by Sewer56** [Nexus-Mods/NexusMods.SingleProcessApp#10]
# Question: Use of Fixed Port Ranges

This is essentially PR Feedback, since nobody reviewed the library code before.

## Context

Currently the library has a default TCP range in range 10000 and 20000 (configurable via `SingleProcessSettings`). Upon creation of host, the library will select a port in the given range, and try to create a server. 

## Question

Is there a specific reason for not opting to use Port 0 for automatic assignment by the Operating System (OS)? This should work consistently on all platforms we support and be more reliable.

Given that the actual in-use port is managed through a synchronization file (i.e. we read it from Memory Mapped File), the choice of port we use really doesn't matter; so I'm not really sure why it's currently restricted by default.

I'm curious if there's any specific reason, as it may be a good learning opportunity.

**Comment by halgari** [comment]
Nope, just didn't know about port 0, this would be a good change
