### ISSUE TITLE
Bug: Clients fail to connect to existing host if `TryStartMainAsync` is called late because the Host ceases to listen.

### ISSUE THREAD

**Issue by Sewer56** [Nexus-Mods/NexusMods.SingleProcessApp#12]
# Bug Report

This will be fixed if the proposed redesign in #7 happens.

### Context

If the library receives no connections within the last `SingleProcessSettings.StayRunningTimeout`, it will cease listening for any new clients. [Because `ShouldExit` will return true.](https://github.com/Nexus-Mods/NexusMods.SingleProcessApp/blob/7990d2be7af068b25234a2a9f35f45eb4610649d/src/NexusMods.SingleProcess/MainProcessDirector.cs#L164C1-L164C1)

### Bug

Because `_lastConnection` is assigned upon creation of `MainProcessDirector`, if there is a gap longer than `StayRunningTimeout` between object creation and calling `TryStartMainAsync`, no clients will be able to connect because `DateTime.UtcNow - _lastConnection > Settings.StayRunningTimeout` will cause `ShouldExit`  to return false.

## Steps to Reproduce
1. Start a long running GUI application.
2. Simulate a load (Sleep) to delay calling of `TryStartMainAsync`.
3. Client can never connect.

## Expected Behaviour

The `MainProcessDirector` should maintain its ability to connect with new clients even if there's a delay in starting it up. 

## Note

While this behaviour is unlikely to realistically happen, it still is, by all means a bug.

**Comment by halgari** [comment]
This is already handled by the `ClientConnectTimeout` which I've change the default of to 1 minute to reduce the chances of this happening.
