### ISSUE TITLE
Performance: Slow CLI Feedback Due to High Latency in Handling Individual Print Commands

### ISSUE THREAD

**Issue by Sewer56** [Nexus-Mods/NexusMods.SingleProcessApp#9]
# Improvement: High Delay in Output Print

## Currently 

When executing commands in applications that use this library, i.e. `dotnet run -- --help`, there 
is a noticeable high delay in the output. On the Nexus App, it can take 10 seconds to print out the 
entire 'help' page.

## We Want

Reasonably fast CLI output, with very minimal delay.  

We should ideally aim to reduce the latency of each individual print command, such that printing any given
possible sequence of console commands is as fast as possible.

### Runtime

```pwsh
Measure-Command { dotnet run --no-build -- --help }

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 12
Milliseconds      : 860
Ticks             : 128609377
TotalDays         : 0.000148853445601852
TotalHours        : 0.00357248269444444
TotalMinutes      : 0.214348961666667
TotalSeconds      : 12.8609377
TotalMilliseconds : 12860.9377
```

10 of the 12 seconds are spent rendering help (see logs).

#### Cause

The suspected cause might be related to using acknowledgements with TCP in `ProxyConsole.Serializer`. 

When using TCP, data can be delayed for sending for the purposes of batching into larger chunks; 
this is to increase the overall throughput; as TCP is an algorithm that prioritises high, reliable 
throughput over low latency. Add acknowledgements to that, any now only 1 message may be transferred
at any given moment.

The problem is exacerbated by the fact that printing an individual line consists of many individual
'print' commands (e.g. for whitespace, different colours, etc.). 

#### Solution

A decent solution without major code difference could be achieved by altering how we use TCP. 

The following solutions come to mind:
- No acknowledgements for messages without response.
  - TCP is ordered, so any message+response will arrive in same order as sent.
  - Render calls make huge majority of the messages, so this makes sense. 
- Disabling Nagle's Algorithm (batching of data for sending).

The removal of Ack(s) alone would probably fix most of the issue alone. Performance after that will likely
be good enough.

#### 'Proper Solution'

TCP is supposed to be used for streams of data, not individual messages; and the data we are sending is
ultimately message based rather than stream based. 

For instance, we don't send `stdout` itself as a stream, but lists of instructions of how to append 
to `stdout` (e.g. print this, print that). TCP is not designed for this.

Ideally something like this really ought to be implemented using a 'reliable' implementation of UDP 
instead that sends packets in order. If response is needed, then requests can carry a unique sequence number so they can be individually distinguished. This allows for asynchronous handling of multiple requests at once.

(Technically the 'real proper' solution is TCP for stdout/stderr stream, and UDP for the rest, but that would be too annoying to work with.)

In any case, this is provided just as additional feedback, not doing ack(s) for messages without responses (as to not stall the stream) will get us most of the way there.

## Misc Note

Current user experience feels like using GPT-4, with the way it renders individual tokens, lol.

**Comment by halgari** [comment]
I don't see this behavior on Windows. The help displays almost instantly, I think there is a delay in how long it takes `Measure-Command` to exit due to it not finishing until all the child processes have started, But the text of `--help` is way less than a second.

**Comment by Sewer56** [comment]
https://github.com/Nexus-Mods/NexusMods.SingleProcessApp/assets/6697380/b0ca48ac-9e80-4961-9e74-10e581d40a06

Current behaviour on Linux (for reference).

Yes, there is a delay with `Measure-Command` 😉, which is why I explicitly `10 out of 12` seconds in the opening post :p

**Comment by halgari** [comment]
I'll probably start with debugging this on Linux to figure out where the actual slow parts are. I'm not sure why it would be this slow. Once we confirm where the slowdown is we can figure out how to optmize it, because as I stated, it's instant on Windows.

**Comment by halgari** [comment]
I don't get this effect on the SteamDeck either. This is on SteamDeck via SSH: 

![alacritty_DqF1fjUY46](https://github.com/Nexus-Mods/NexusMods.SingleProcessApp/assets/654621/6f8a7653-9211-4d49-8609-805a28420861)

**Comment by erri120** [comment]
I can reproduce this.

**Comment by Sewer56** [comment]
As I predicted, this was caused by Nagle's Algorithm.

https://github.com/Nexus-Mods/NexusMods.SingleProcessApp/assets/6697380/740ee18f-e684-4060-a7d5-9c0c9cc3ea0c

In any case, I disabled Nagle's and the speed shot back up instantly. Then I disabled Ack(s) on render calls for another small improvement in speed.

In other words, I did exactly as I outlined in `Solution` in the opening post. You can find the justifications there.
